# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tython < Formula
  desc "Tython supports testing and applying (i.e. running) user-created SaC blueprints. This can be done locally on your own machine or through integrations with oak9."
  homepage "https://oak9.io/"
  version "0.0.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com//oak9io/tython/releases/download/v0.0.2/tython_0.0.2_darwin_amd64.tar.gz"
      sha256 "d5b33524eb3177891100c74d635508b9fe87aec15c3fbf8a2ff40a7129481615"

      def install
        bin.install "tython"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com//oak9io/tython/releases/download/v0.0.2/tython_0.0.2_darwin_arm64.tar.gz"
      sha256 "b8f825b9acf2f390c1abbaccfbe357e9155cb05229fd8c458fd5416f6df6c8d6"

      def install
        bin.install "tython"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com//oak9io/tython/releases/download/v0.0.2/tython_0.0.2_linux_arm64.tar.gz"
      sha256 "06a8d9d9582fabe0f37f5c4f0186b842b81c4acd81c3535b943610d80234bed5"

      def install
        bin.install "tython"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com//oak9io/tython/releases/download/v0.0.2/tython_0.0.2_linux_amd64.tar.gz"
      sha256 "e02f3075618eb609098ea52ae38f39282ec2ce60cfccaf3f2cc138cfdb7de0f0"

      def install
        bin.install "tython"
      end
    end
  end

  def caveats
    <<~EOS
      ./tython -h or ./tython.exe -h
    EOS
  end
end
